September 2023 GMC Update
rocket-pool/RPIPs pull request #76
Opened 2023-09-21 20:11 UTC by shfryn

2023-09-26 22:30 UTC, Valdorff commented
Generally looks good

2023-09-26 22:30 UTC, Valdorff requested changes

2023-09-26 22:30 UTC, Valdorff commented on RPIPs/RPIP-29.md
> +| Bounty Award Code                                                                                                   | Bounty Title            | Date of Award | Awardee(s) | Payment Address
Should be proposer not Awardee?

2023-09-26 22:56 UTC, shfryn commented on RPIPs/RPIP-29.md
> +| Bounty Award Code                                                                                                   | Bounty Title            | Date of Award | Awardee(s) | Payment Address
done

2023-09-27 20:21 UTC, Valdorff approved these changes

2023-09-27 20:21 UTC, merged